// Mocks generated by Mockito 5.1.0 from annotations
// in the_boring_app/test/features/random_activity/domain/usecases/get_random_activity_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:the_boring_app/core/errors/failures.dart' as _i5;
import 'package:the_boring_app/features/random_activity/domain/entities/random_activity.dart'
    as _i6;
import 'package:the_boring_app/features/random_activity/domain/repositories/random_activity_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [RandomActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomActivityRepository extends _i1.Mock
    implements _i3.RandomActivityRepository {
  MockRandomActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RandomActivity?>>
      getRandomActivity() => (super.noSuchMethod(
              Invocation.method(#getRandomActivity, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.RandomActivity?>>.value(
                      _FakeEither_0<_i5.Failure, _i6.RandomActivity?>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.RandomActivity?>>);
}
